### ISSUE TITLE
Hasura v2

### ISSUE THREAD

**Issue by ManUtopiK** [SocialGouv/hasura-permissions-viewer#22]
It seems not compatible with Hasura v2 😞 

Also, why not exporting [hasura metadata api](https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/manage-metadata.html#export-metadata) instead of using .yaml?

**Comment by revolunet** [comment]
Not yet compatible with v2 yet sorry :/

export_metadata used to output as YAML, but v2 migration should be a good occasion to use JSON instead

Happy to help land a PR :)

**Comment by revolunet** [comment]
fixed in latest : https://socialgouv.github.io/hasura-permissions-viewer/
